# ──────────────────────────────────────────────
# Cannelloni protocol constants
# ──────────────────────────────────────────────
CANNELLONI_VERSION = 2
CANNELLONI_OP_DATA = 0
CANNELLONI_HEADER_SIZE = 5

# ──────────────────────────────────────────────
# CAN constants
# ──────────────────────────────────────────────
CAN_EFF_FLAG = 0x80000000
CAN_EFF_MASK = 0x1FFFFFFF

# ──────────────────────────────────────────────
# DroneCAN / UAVCAN v0 constants
# ──────────────────────────────────────────────
DRONECAN_NODE_ID = 2
DRONECAN_NODE_NAME = "gateway.mock"
DRONECAN_NODESTATUS_DTID = 341
DRONECAN_GETNODEINFO_DTID = 1
DRONECAN_ALLOCATION_DTID = 1
DRONECAN_GNSS_FIX2_DTID = 1063
DRONECAN_ICE_RECIPROCATING_STATUS_DTID = 1120
DRONECAN_GETNODEINFO_SIGNATURE = 0xEE468A8121C46A9E
DRONECAN_ALLOCATION_SIGNATURE = 0x0B2A812620A11D40
DRONECAN_GNSS_FIX2_SIGNATURE = 0xCA41E7000F37435F
DRONECAN_ICE_RECIPROCATING_STATUS_SIGNATURE = 0xD38AA3EE75537EC6
DRONECAN_PRIORITY_DEFAULT = 4

HEALTH_OK = 0
MODE_OPERATIONAL = 0

